"""Final update for 3.9

Revision ID: cfc55f288e58
Revises: 9ac1352bdad4
Create Date: 2025-07-29 20:36:55.413938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfc55f288e58'
down_revision: Union[str, Sequence[str], None] = '9ac1352bdad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chaos_stats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('high_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('daily_quests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('quest', sa.Text(), nullable=False),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Integer(), nullable=False),
    sa.Column('reward_coin', sa.Integer(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('reward_coin', sa.Integer(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_role', sa.String(), nullable=True),
    sa.Column('reward_badge', sa.String(), nullable=True),
    sa.Column('ends_at', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('giftcodes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=True),
    sa.Column('items', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('per_user_cooldown', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('allowed_user_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_pay', sa.Integer(), nullable=False),
    sa.Column('mastery_req', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minigames',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_played', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('last_game', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('secret_unlocks',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('unlock_key', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'unlock_key')
    )
    op.create_table('thank_logs',
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('sender_id', 'receiver_id')
    )
    op.create_table('trivia_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trust_logs',
    sa.Column('giver_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('giver_id', 'receiver_id')
    )
    op.create_table('user_events',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('claimed_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'event_key')
    )
    op.create_table('user_giftcodes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('used_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'code')
    )
    op.create_table('user_quests',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_key', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('req', sa.Integer(), nullable=True),
    sa.Column('reward_coin', sa.Integer(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'quest_key')
    )
    op.create_table('user_jobs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('mastery', sa.Integer(), nullable=False),
    sa.Column('job_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('profile_banner_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('custom_field_title', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('custom_field_value', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('profile_moods', sa.JSON(), server_default='{}', nullable=False))
    op.drop_column('users', 'profile_theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_theme', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_moods')
    op.drop_column('users', 'custom_field_value')
    op.drop_column('users', 'custom_field_title')
    op.drop_column('users', 'profile_banner_url')
    op.drop_table('user_jobs')
    op.drop_table('user_quests')
    op.drop_table('user_giftcodes')
    op.drop_table('user_events')
    op.drop_table('trust_logs')
    op.drop_table('trivia_questions')
    op.drop_table('thank_logs')
    op.drop_table('secret_unlocks')
    op.drop_table('minigames')
    op.drop_table('jobs')
    op.drop_table('giftcodes')
    op.drop_table('events')
    op.drop_table('daily_quests')
    op.drop_table('chaos_stats')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
